exports.tableTypes = {
  "TABLE_CATEGORIES": "TABLE_CATEGORIES",
  "TABLE_BRANDS": "TABLE_BRANDS",
  "TABLE_INVOICES": "TABLE_INVOICES",
  "TABLE_CUSTOMERS": "TABLE_CUSTOMERS",
  "TABLE_INVOICE_PRODUCTS": "TABLE_INVOICE_PRODUCTS",
  "TABLE_ITEMS": "TABLE_ITEMS",
  "TABLE_ITEM_DOCUMENTS": "TABLE_ITEM_DOCUMENTS",
}